import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import MobileNavbar from "./components/MobileNavbar";
import { Sidebar } from "./components/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Finance AI",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
        >
          <Theme appearance="dark">
            <div className="relative md:hidden z-50">
              <MobileNavbar />
            </div>
            <section className="flex">
              <div className="hidden md:block">
                <Sidebar />
              </div>
              <div className="mt-14 md:mt-0 md:ml-96 w-full">{children}</div>
            </section>
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
